---
- name: Install consul
  ansible.builtin.include_role:
    name: andrewrothstein.consul
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: create consul group
  become: true
  become_user: root
  ansible.builtin.group:
    name: '{{ consul_agent_group }}'
    state: present

- name: create consul user
  become: true
  become_user: root
  ansible.builtin.user:
    name: '{{ consul_agent_user }}'
    group: '{{ consul_agent_group }}'
    home: '{{ consul_agent_data_dir }}'
    state: present

- name: create directories
  become: true
  become_user: root
  with_items:
    - d: '{{ consul_agent_etc_dir }}'
      m: '755'
    - d: '{{ consul_agent_data_dir }}'
      m: '755'
    - d: '{{ consul_agent_etc_pki_dir }}'
      m: '700'
  ansible.builtin.file:
    path: '{{ item.d }}'
    state: directory
    owner: '{{ consul_agent_user }}'
    group: '{{ consul_agent_group }}'
    mode: '{{ item.m }}'

- name: install keys/certs
  when: consul_agent_secure
  ansible.builtin.include_role:
    name: andrewrothstein.sshkey
  vars:
    sshkey_become: True
    sshkey_pki_dir: '{{ consul_agent_pki_dir }}'
    sshkey_target_perms:
      owner: '{{ consul_agent_user }}'
      group: '{{ consul_agent_group }}'
    sshkey_target_dir: '{{ consul_agent_etc_pki_dir }}'
    sshkey_override_target_cert: cert.pem
    sshkey_override_target_key: key.pem

- name: configure templates...
  become: true
  become_user: root
  ansible.builtin.template:
    src: '{{ consul_agent_template }}.j2'
    dest: '{{ consul_agent_etc_dir }}/consul.json'
    owner: '{{ consul_agent_user }}'
    group: '{{ consul_agent_group }}'
    mode: 0644

- ansible.builtin.include_tasks: '{{ consul_agent_init | default("systemd") }}.yml'

- name: launch consul service
  become: true
  become_user: root
  when: consul_agent_activate
  ansible.builtin.service:
    name: consul
    enabled: true
    state: started
